name: myActionsTest
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  ENV_TYPE: DEV
  APP_USER: shasha
  

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "hi"  
      - name: Step 2
        uses: actions/checkout@v6.0.2
      - name: Step 3
        run : |
          mkdir -p artifacts
          echo 'pwd' >> myartifact.txt
          echo 'ls-lrt' >> artifacts/multi.txt
          echo 'hostname' >> artifacts/hostname.txt
          ls
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myTextFile
          path: ./myartifact.txt

      - name: the download directory
        uses: actions/upload-artifact@v4
        with:
          name: myArtifactDirectory
          path: artifacts/
        
      - name: upload multiple artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: mutipleFiles
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt
            
  job2:
    name: Job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: creating a custom folder for artifacts
        run: |
          mkdir -p single_file
      - name: Step 1 Checking current directory
        run: |
          pwd
          ls -ltr
      - name: download single artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: myArtifactDirectory
          path: single_file
      - name: check the artifacts
        run: |
          pwd
          ls -ltr single_file
      - name: reffering env variables
        run: |
          echo "[INFO] Running deployment for $ENV_TYPE with $APP_USER"
      - name: ref Repo Secrets
        run: |
          echo "app password is ${{ secrets.APP_PASSWORD }}"


      
    


    
